### ISSUE TITLE
Is APPLE_AUTOMATION_BEARER_TOKEN and PODCAST_ID both needed?

### ISSUE THREAD

**Issue by woolfg** [openpodcast/pipelines#22]
Do we still need both of those env vars, as the popdcast name is mapped from the token in https://github.com/openpodcast/apple-automation/blob/main/.env.sample ?

```
APPLE_AUTOMATION_BEARER_TOKEN=<APPLE_AUTOMATION_BEARER_TOKEN>
PODCAST_ID=<PODCAST_ID>
```

https://github.com/openpodcast/open/blob/1fadf0a55602799537e1737751606090448c2a48/apple/.env.sample#L3

**Comment by mre** [comment]
👍 
Thanks for fixing that in https://github.com/openpodcast/pipelines/pull/24.
