### ISSUE TITLE
catch login error when cookie is outdated and report it so we can process it in grafana

### ISSUE THREAD

**Issue by woolfg** [openpodcast/pipelines#83]
the connector raises `raise CredentialsExpired("Login required (credentials cookie expired?)")` when the cookie is no longer valid and the login is not possible. this auth is called with the first request which is initiated in a thread by the pipeline.

**Comment by woolfg** [comment]
@mre what is idiomatic and where should I catch the error in pipeline as the calls are hidden in the worker thread

**Comment by mre** [comment]
Outside the worker, we could catch this very specific error, log it, send a metric to Grafana, and exit with a non-zero status code. I'd deem that to be relatively pythonic.
